language: rust
sudo: false

cache: cargo

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - nightly

script:
  - cargo build
  - cargo doc
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo bench;
    fi
