[package]
name = "clit-rs"
description = "Command line tool allow you to access twitter"
version = "0.1.0"
authors = ["Vanessa McHale <tmchale@wisc.edu>"]
license-file = "LICENSE"
exclude = [ ".gitignore" ]
readme = "README.md"
repository = "https://github.com/vmchale/clit-rs"
documentation = "https://github.com/vmchale/clit-rs#README"
homepage = "https://github.com/vmchale/clit-rs"

[dependencies]
oauth-client-fix = "0.1"
nom = "2.1"
colored = "1.4"
clap = {version = "2.19", features = ["yaml"]}

[lib]
name = "libclit"
path = "src/lib.rs"

[[bin]]
name = "tweet"
path = "src/main.rs"
