[package]
name = "clit-rs"
version = "0.1.0"
authors = ["Vanessa McHale <tmchale@wisc.edu>"]

[dependencies]
oauth-client = { git = "https://github.com/justinj/oauth-client-rs", branch = "master" }
nom = "2.1"
colored = "1.4"
clap = {version = "2.19", features = ["yaml"]}

[lib]
name = "libclit"
path = "src/lib.rs"

[[bin]]
name = "tweet"
path = "src/main.rs"
